# Generated by Django 4.2.6 on 2023-10-18 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serie_a', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atalanta',
            name='number',
            field=models.PositiveIntegerField(),
        ),
    ]
