# Generated by Django 4.2.6 on 2023-10-19 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serie_a', '0003_bologna'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bologna',
            new_name='Cagliari',
        ),
        migrations.AlterModelOptions(
            name='cagliari',
            options={'verbose_name': 'Cagliari', 'verbose_name_plural': 'Cagliari'},
        ),
    ]
