# Generated by Django 4.2.6 on 2023-10-15 15:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Work', '0003_food_football'),
    ]

    operations = [
        migrations.AddField(
            model_name='football',
            name='goal_scorer',
            field=models.CharField(default=django.utils.timezone.now, max_length=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='football',
            name='line_up',
            field=models.TextField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
