# Generated by Django 4.2.6 on 2023-10-15 15:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Work', '0004_football_goal_scorer_football_line_up_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='person',
            name='profession',
            field=models.CharField(default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='football',
            name='line_up',
            field=models.TextField(max_length=5000),
        ),
    ]
