# Generated by Django 4.2.6 on 2023-10-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Work', '0005_remove_person_birth_date_person_profession_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(max_length=30)),
                ('number_of_feet', models.PositiveIntegerField()),
                ('food_type', models.TextField(max_length=1000)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clothe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.FloatField()),
                ('for_Boy_or_Girl', models.CharField(max_length=10)),
                ('price', models.PositiveIntegerField()),
                ('made_in', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Perfume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('made_in', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, unique=True)),
                ('made_in', models.CharField(max_length=50)),
                ('RAM', models.PositiveIntegerField()),
                ('processor', models.CharField(max_length=35)),
                ('color', models.CharField(max_length=35)),
                ('description', models.TextField(blank=True, max_length=10000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Programming_languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_type', models.CharField(max_length=30, unique=True)),
                ('intended_for', models.TextField(max_length=1000)),
                ('description', models.TextField(blank=True, max_length=15000, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
